### ISSUE TITLE
Having trouble installing on 3.2.2

### ISSUE THREAD

**Issue by royburst** [jalvesaq/colorout#10]
Works fine on 3.1.2 though. Is this known or just an issue on my end somehow? Let me know if you need more details. Game-changing package though!

**Comment by ankur-gupta** [comment]
+1 on game-changing

**Comment by jalvesaq** [comment]
It installs with no problem here: Ubuntu 16.10, R-3.3.2. Do you see any error message?

**Comment by jalvesaq** [comment]
I had to reinstall some packages when I upgraded R recently. Please, reopen the issue if reinstalling colorout does not fix the problem.
