### ISSUE TITLE
Load only in a terminal emulator, not in RSTudio?

### ISSUE THREAD

**Issue by for-coursera** [jalvesaq/colorout#11]
Is it possible to achieve that somehow? Via configs or command-line switches may be?

I mean, is it possible to wrap `library(colorout)` in `.Rprofile` in some conditionals, may be? Or to create some command line terminal-specific alias for R?

**Comment by bdwyer2** [comment]
```if(Sys.getenv("TERM") %in% c("xterm-256color", "xterm")) {
        library("colorout")
}```

**Comment by bdwyer2** [comment]
```
if(Sys.getenv("TERM") %in% c("xterm-256color", "xterm")) {
        library("colorout")
```

**Comment by for-coursera** [comment]
Super, thanks!
