### ISSUE TITLE
Wrong display of characters or colors

### ISSUE THREAD

**Issue by cpfaff** [jalvesaq/colorout#14]
He

I am using 

* VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 07:13:39), Included patches: 1-1415
* tmux 2.6
* colorout at v1.2-2

Mostly this works fine. However I encountered some characters are messed up in the output in the console when using the dplyr package with colorout (without colorout the output is fine). An example

```R
install.packages(dplyr)
require(dplyr)
cars %>% as_tibble()
38;5;246m# A tibble: 50 x 2                                                                                                                                                                      
   speed  dist
38;5;246m   <dbl> <dbl>
38;5;250m 1  4.00  2.00
38;5;250m 2  4.00 10.0 
38;5;250m 3  7.00  4.00
38;5;250m 4  7.00 22.0 
38;5;250m 5  8.00 16.0 
38;5;250m 6  9.00 10.0 
38;5;250m 7 10.0  18.0 
38;5;250m 8 10.0  26.0 
38;5;250m 9 10.0  34.0 
38;5;250m10 11.0  17.0 
38;5;246m# ... with 40 more rows
```

Without coloring

```R
cars %>% as_tibble()
# A tibble: 50 x 2                                                                                                                                                                               
   speed  dist
   <dbl> <dbl>
 1  4.00  2.00
 2  4.00 10.0 
 3  7.00  4.00
 4  7.00 22.0 
 5  8.00 16.0 
 6  9.00 10.0 
 7 10.0  18.0                                                                                                                                                                                    
 8 10.0  26.0                                                                                                                                                                                    
 9 10.0  34.0 
10 11.0  17.0 
# ... with 40 more rows
> 
```

Other information about my config:

* Locales:

```
LANG=en_US.UTF-8
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

```R
Sys.getlocale()
[1] "LC_CTYPE=de_DE.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C"
```

I am a little bit lost with that one. Do you have any idea what could causes this?

**Comment by jalvesaq** [comment]
The same code works fine here. Did you set the colorout's output colors?

**Comment by jalvesaq** [comment]
What is your terminal emulator?

**Comment by cpfaff** [comment]
The terminal emulator is rxvt-unicode. I did not touch the color output of colorout.

**Comment by cpfaff** [comment]
I will. Report back in a sec

**Comment by cpfaff** [comment]
Cool the master version works and ignores the already colored part. Now I also found out why there were problems at all. The tibble package recently added support for coloring using the crayon package. That is why the output  was already colored. 

https://github.com/tidyverse/tibble/issues/346

If you want colorout to take over again set 

options(crayon.enabled = FALSE)

and everything works as usual. 

Thanks!

**Comment by jalvesaq** [comment]
Recently RStudio added support to ANSI colors. So, we should expect more packages colorizing their outputs. And I will release the new version of colorout soon. I'm only waiting a few weeks to people report bugs.

**Comment by cpfaff** [comment]
I see. Thanks for you work on this.

**Comment by lcolladotor** [comment]
Awesome! https://github.com/jalvesaq/colorout/commit/020a14dbb51177bc3dc3d1601bfb3be0abca2006 fixed an issue we were seeing with `git bash` on a Windows machine. Turns out we just had to update `colorout`. 

(just posting this in case other `git bash` users run into the same issue)
