### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by wigust** [jalvesaq/colorout#15]
Hello,

Thank you for this package!

Please, could you include a LICENSE file as R/colorout.R says
```
# It is distributed under the GNU General Public License.
# See the file ../LICENSE for details.
```

Also maybe push as a new tag after adding a license file?

Thanks,
Oleg.

**Comment by jalvesaq** [comment]
Done!

**Comment by wigust** [comment]
> Done!

Thank you!

I'll close the issue.

Oleg.
