### ISSUE TITLE
Progress bar broken when colorout loaded

### ISSUE THREAD

**Issue by LiNk-NY** [jalvesaq/colorout#16]
Hi Jakson, @jalvesaq 

Thanks for making this package. It makes output fun to read :grinning: 

My issue is that when reading in a large file, the progress bar continually includes line
breaks rather than staying in place.     

It starts looking like this:
```
|=======                                                                                                                    |   |=======                                                                                                                   |  5|========                                                                                                                  |  5%    |========                                                                                                                  |  5%    1|========
```

Rather than: 
```
 |===================| 100% 15 MB
```

I'm referring to functionality found in `readr`, such as `read_tsv` but this works fine when
`colorout` is not loaded.

For example data files, please see here: http://www.cbioportal.org/data_sets.jsp

Regards,
Marcel

**Comment by LiNk-NY** [comment]
Sorry, I forgot to mention that I am using Rstudio.

**Comment by jalvesaq** [comment]
Now I can replicate the issue, but since it works well in different terminal emulators on Linux (xterm, gnome-terminal, Neovim's built-in terminal inside Tmux running in gnome-terminal) I think you should report the issue to RStudio.

**Comment by LiNk-NY** [comment]
Thanks for looking into it! I'll close the issue. 
Best regards,
Marcel

**Comment by gowachin** [comment]
Does this issue have been solved with Rstudio ? I have the same issue, and sometimes miss printing in Rstudio (like something print inside the table I print in console)

**Comment by jalvesaq** [comment]
@gowachin, I think that nobody has ever reported the issue to RStudio team. So, the it may never get solved.
