### ISSUE TITLE
colorout is incompatible with crayon

### ISSUE THREAD

**Issue by alaindanet** [jalvesaq/colorout#17]
Hi,

I have found a incompatibility between
[`crayon`](https://github.com/r-lib/crayon) and `colorout` which you can find
[here](https://github.com/r-lib/crayon/issues/68).

It is a bit annoying because I really like the way that colorout colors output
but on the other side, the `tibble` and `testthat` packages for example are
using the package `crayon`. 

Thank you so much for your work!

**Comment by jalvesaq** [comment]
What is your version of colorout?

**Comment by alaindanet** [comment]
0.9.9

**Comment by jalvesaq** [comment]
https://github.com/jalvesaq/colorout/releases

**Comment by alaindanet** [comment]
It works perfectly with the 1.2.0!

Thank you very much, I will update the issue on the `crayon` repo!
