### ISSUE TITLE
Recolor past output?

### ISSUE THREAD

**Issue by balachia** [jalvesaq/colorout#18]
I switch terminal color schemes between light (white background) and dark (black) during the course of the day. When I switch, I can call colorout to change the color scheme for future output (via `setOutputColors256`). But this does not affect any past output, parts of which become impossible to see.

Is there any way to recolor the past output? For context, I'm usually using R through Tmux if that changes anything.

**Comment by jalvesaq** [comment]
As far as I know, colors 0-15 are defined by your terminal color scheme, but colors 16-255 have fixed RGB values. What happens if you call `setOutputColors` with all values between 0 and 15?

**Comment by balachia** [comment]
That does work, though I was hesitating to remap 0-15 just for R, especially if there were some alternative. But yes, putting only 0-15 in `setOutputColors` and then changing the terminal colors does cause past R output to change.

I did notice a small bug in GetColorCode though:

https://github.com/jalvesaq/colorout/blob/27d122a450c0c7859ac10b5372035c02eb8e514b/R/colorout.R#L116-L127

You're checking for `if (x[3])` and `if (x[2])` which evaluates to false if I try to set something to terminal color 0 (i.e. black), and instead reverts to the terminal foreground/background color. That is, it's impossible to get the ;30 and ;40 escape codes. There's also no way to set a color to terminal foreground/background directly, i.e. to get the ;39 or ;49 escape codes. Would it make sense to change those checks to something like `if (!is.na(x[3])) ... else colstr <- paste0(colstr, ";39")` or something instead? That would allow a user to pass in NA to revert to default terminal fg/bg.

**Comment by jalvesaq** [comment]
Is it OK now?

**Comment by balachia** [comment]
Yes, thank you, this looks great.
