### ISSUE TITLE
Background color of black is not black

### ISSUE THREAD

**Issue by gvfarns** [jalvesaq/colorout#20]
Using R in a gnome-terminal window under Fedora 28.

Using recent versions of colorout, the background color of output from R is set to a grey color instead of the black that is part of my terminal color scheme.   My outputcolors are set thus:

    setOutputColors(                                                                                                                          
                    normal=c(0,0,6),                                                                                                          
                    number=c(1,0,6),                                                                                                          
                    negnum=c(1,0,5),                                                                                                          
                    date=c(0,0,3),                                                                                                            
                    string=c(1,0,4),                                                                                                          
                    const=c(1,0,3),                                                                                                           
                    stderror=c(0,0,4),                                                                                                        
                    warn=c(0,0,1),                                                                                                            
                    error=c(0,1,7),                                                                                                           
                    verbose=FALSE                                                                                                             
                   ) 

In each case, the background color is 0 but this is not being translated to black

![screenshot1](https://user-images.githubusercontent.com/3987806/40856407-6588a8d6-659d-11e8-9e3d-5fe99633a425.png)

The output of show256Colors() does not seem to have grey for color 0.  

![show256](https://user-images.githubusercontent.com/3987806/40856224-bc2e3aa8-659c-11e8-8512-56d7032ff4af.png)

I'm not certain whether there was a change in colorout or in my OS that caused this but would appreciate any guidance you can provide.  Thanks.

**Comment by jalvesaq** [comment]
I copied and pasted your `setOutputColors` command into my `~.Rprofile` but I couldn't replicate the issue. The output of `gnome-terminal --version` here is:
```
GNOME Terminal 3.28.1 using VTE 0.52.1 +GNUTLS -PCRE2
```

**Comment by gvfarns** [comment]
Here's mine:

~> gnome-terminal --version
# GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS

These might be more relevant:

![settings](https://user-images.githubusercontent.com/3987806/40858894-78a755c2-65a5-11e8-8113-55cf20634101.png)

I'll try changing some of these and see if it makes a difference.

**Comment by gvfarns** [comment]
Ok, if you change the built-in palette scheme from "Tango" to "Linux Terminal," it changes the backgrounds in question.  That's a good fix.  Not sure whether it has implications for colorout--I'm not sure what "palette" really is as opposed to the text and background color above. 

![fixed](https://user-images.githubusercontent.com/3987806/40859079-2664a7fa-65a6-11e8-8527-8208ec8ece40.png)

At least we know it was the OS that changed, not colorout.  Thanks for looking at this with me and sorry for the trouble.
