### ISSUE TITLE
colorout for windows

### ISSUE THREAD

**Issue by 777uliahshafar** [jalvesaq/colorout#35]
Hi there, I really like this package, however I could not use it anymore since I am using windows. Is there any package out there that is similar to this for windows user. 
Thank you.

**Comment by jalvesaq** [comment]
The pointers used by _colorout_ to replace the functions that output text to `stdout` and `stderr` don't exist in `rterm.exe`. So, I guess that on Windows it would be necessary to create a real front-end for R.

**Comment by 777uliahshafar** [comment]
Thank you for your answer, It is slightly hard to read the same color result though.
