### ISSUE TITLE
Configuring the colorscheme makes my formatter and lsp exit

### ISSUE THREAD

**Issue by life00** [jalvesaq/colorout#39]
When I have:

```R
colorout::setOutputColors(
# ...
)
```
Set to anything in Rprofile my LSP ([`r-languageserver`](https://github.com/REditorSupport/languageserver)) and formatter ([`styler`](https://github.com/r-lib/styler)) just exit and refuse to work.

Here are the errors:

`r-languageserver`:

```
[ERROR][2024-02-24 19:40:25] .../vim/lsp/rpc.lua:734	"rpc"	"r-languageserver"	"stderr"	'Error in .C("colorout_SetZero", z, PACKAGE = "colorout") : \n  "colorout_SetZero" not available for .C() for package "colorout"\nCalls: <Anonymous> -> setZero\nExecution halted\n'
```

`styler`:

```
19:40:38[ERROR] Formatter 'my_styler' error: Error in .C("colorout_SetZero", z, PACKAGE = "colorout") : 
  "colorout_SetZero" not available for .C() for package "colorout"
Calls: <Anonymous> -> setZero
Execution halted
```

When I do not configure the colorscheme everything works perfectly, but obviously I wish I could configure my colorscheme and have everything working. Any ideas how to fix this?

**Comment by life00** [comment]
I should probably also provide some additional context. I am running Fedora Linux 39 aarch64, and editor is neovim. I installed manually from source into a local directory.

Build logs:

```
* installing *source* package ‘colorout’ ...
** using staged installation
** libs
using C compiler: ‘gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)’
gcc -I"/usr/include/R" -DNDEBUG   -I/usr/local/include    -fPIC  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer   -c colorout.c -o colorout.o
colorout.c: In function ‘isnumber’:
colorout.c:87:50: warning: comparison of constant ‘45’ with boolean expression is always false [-Wbool-compare]
   87 |     if(i > 0 && !iswhitespace(b[i-1]) && !b[i-1] == '-')
      |                                                  ^~
colorout.c:87:50: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
colorout.c:87:42: note: add parentheses around left hand side expression to silence this warning
   87 |     if(i > 0 && !iswhitespace(b[i-1]) && !b[i-1] == '-')
      |                                          ^~~~~~~
      |                                          (      )
gcc -shared -L/usr/lib64/R/lib -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -o colorout.so colorout.o -L/usr/lib64/R/lib -lR
installing to /home/user/tmp/test/00LOCK-colorout/00new/colorout/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Warning message:
.onUnload failed in unloadNamespace() for 'colorout', details:
  call: .C("colorout_noColorOutput", PACKAGE = "colorout")
  error: "colorout_noColorOutput" not available for .C() for package "colorout"
** help
*** installing help indices
  converting help for package ‘colorout’
    finding HTML links ... done
    ColorOut                                html
    addPattern                              html
    colorout-package                        html
    deletePattern                           html
    isColorOut                              html
    listPatterns                            html
    noColorOut                              html
    setOutputColors                         html
    setOutputColors256                      html
    setZero                                 html
    show256Colors                           html
    unsetZero                               html
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (colorout)
```

I am not sure if the error and warnings in the logs are related to this issue, but I still consider that the issue may come from compilation given that this is C code and I am running aarch64 with 16k page size which is pretty uncommon.

**Comment by joshuaulrich** [comment]
This is caused by the changes in commit 1080187f9474b71f16c3c0be676de4c54863d1e7. They make it so that the colorout C library is not loaded when the colorout namespace is loaded. So code like below no longer works:

```r
have_colorout <- requireNamespace("colorout", quietly = TRUE)
if (have_colorout) {
    colorout::setOutputColors(verbose = FALSE)
}
## Error in .C("colorout_UnsetZero", PACKAGE = "colorout") : 
##   "colorout_UnsetZero" not available for .C() for package "colorout"
```

I don't know what the changes in that commit were trying to fix, but it will break existing code that follows standard R patterns like the one above.

**Comment by life00** [comment]
You are right. Part of the problem for me was that I was using the latest code from master. Now I installed colorout as  version 1.3-0 and there is no more issues, but there you go some bugs to fix before the new release :)

Build of version 1.3-0 (clean, no issues):

```
* installing *source* package ‘colorout’ ...
** using staged installation
** libs
using C compiler: ‘gcc (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)’
gcc -I"/usr/include/R" -DNDEBUG   -I/usr/local/include    -fPIC  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer   -c colorout.c -o colorout.o
gcc -shared -L/usr/lib64/R/lib -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -o colorout.so colorout.o -L/usr/lib64/R/lib -lR
installing to /home/user/etc/lib/R/library/00LOCK-colorout/00new/colorout/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘colorout’
    finding HTML links ... done
    ColorOut                                html
    addPattern                              html
    colorout-package                        html
    deletePattern                           html
    isColorOut                              html
    listPatterns                            html
    noColorOut                              html
    setOutputColors                         html
    setOutputColors256                      html
    setZero                                 html
    show256Colors                           html
    unsetZero                               html
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (colorout)
```

**Comment by jalvesaq** [comment]
If colorout wasn't loaded, the function isColorOut() was loading the C
library and starting to colorize the output. This was the bug fixed.

The languageserver doesn't benefit of colorized output. So it will be more
efficient if you don't load colorout in this case. Perhaps you could check
isatty(stdout()) before calling any colorout function.

Anyway, I have to avoid the error when a colorout function is called and
the C library isn't loaded. There are two options: (1) load the C library,
(2) return without doing anything. Of course, the first option is more
consistent with the previous behavior, but maybe the previous behavior
could be considered wrong: you were trying to set a colorscheme, not to
start colorizing the output.

**Comment by joshuaulrich** [comment]
> If colorout wasn't loaded, the function isColorOut() was loading the C
> library and starting to colorize the output. This was the bug fixed.

It is standard practice to load the library when the namespace is loaded. Not doing this is unusual and will probably create more cases in colorout that need special handling like you added to `isColorOut()`.

If you think it's wrong to colorize output when the package is _loaded_ then we could remove the call to `ColorOut()` in `.onLoad()`. And then we can require users call `ColorOut()` explicitly when they want to use colorout without _attaching_ the package to the search path. Attaching colorout via `library()` or `require()` will still colorize output automatically because of the call to `ColorOut()` in `.onAttach()`.

Revert commit 1080187f9474b71f16c3c0be676de4c54863d1e7 and then apply the patch below.

```diff
diff --git a/R/colorout.R b/R/colorout.R
index 30436ce..dee845e 100644
--- a/R/colorout.R
+++ b/R/colorout.R
@@ -24,9 +24,7 @@
         options(colorout.verbose = 0)
 
     msg <- testTermForColorOut()
-    if(msg == "OK")
-        ColorOut()
-    else if(getOption("colorout.verbose") > 0){
+    if(msg != "OK" && getOption("colorout.verbose") > 0){
         msg <- paste(gettext("The R output will not be colorized because it seems that your terminal does not support ANSI escape codes.", domain = "R-colorout"),
                      msg)
         warning(msg, call. = FALSE, immediate. = TRUE)
```

Then colorization does not occur when the package namespace and library are loaded, unless `ColorOut()` is called explicitly. For example:

![image](https://github.com/jalvesaq/colorout/assets/1023193/f2d48f52-1b66-406e-a54b-c84fd18804b3)

**Comment by jalvesaq** [comment]
It's wrong to colorize the output when asking if the output is being colorized. It needs to return FALSE, and not start colorizing at https://github.com/R-nvim/R.nvim/blob/main/nvimcom/R/nvimcom.R#L85

Could you do a pull request with your proposal, please? Any solution is good to me, as long as `colorout::isColorOut()` simply returns FALSE.

**Comment by joshuaulrich** [comment]
> Could you do a pull request with your proposal, please?

Done. And I added a test to ensure `colorout::isColorOut()` returns `FALSE` when the package is loaded but not attached.
