### ISSUE TITLE
RStudio

### ISSUE THREAD

**Issue by slowkow** [jalvesaq/colorout#4]
Is it possible to use output colored by `colorout` in the RStudio terminal? Would this require changes in the RStudio app?

**Comment by jalvesaq** [comment]
The colorizing of output in RStudio is done by Qt function. I am not sure if a package can replace the function, but I guess that it is not possible. It would be necessary to change RStudio code. Someone has already requested this, but it seems that RStudio team is not convinced of its usefulness yet:

https://support.rstudio.com/hc/communities/public/questions/200658723-Colored-text-output-in-the-RStudio-console

**Comment by jalvesaq** [comment]
Note: the colorout package is intended to colorize R output in terminal emulators that accept ANSI escape codes. It would not be difficult to adapt the code of colorout (written in C) to RStudio (written in C++), but this this would be another package.

**Comment by jalvesaq** [comment]
RStudio now accepts ANSI colors, and I am going to commit a change to not disable the colorizing of R output when within RStudio.
