### ISSUE TITLE
different colors for commented lines

### ISSUE THREAD

**Issue by caeu** [jalvesaq/colorout#41]
Is there a way to set different colors for commented lines. If not, I hope it is considered for future implementation.

**Comment by jalvesaq** [comment]
Could you give an example, please? Colorout only colorized the output of R, not the input.

**Comment by caeu** [comment]
This could be because I set, echo=TRUE, print.eval = FALSE which is to avoid an [issue](https://github.com/R-nvim/R.nvim/issues/216) that you answered me in R.nvim related to data.table objects.

Comments get colored only  if I send multiple lines (more than 20), otherwise if less, I get white colored comments.

<img width="1980" alt="image" src="https://github.com/user-attachments/assets/4640d6f8-9362-4291-b8ef-e4987df2c5b0">

**Comment by jalvesaq** [comment]
It's the input being echoed. That is, it's output imitating input.

The goal of `colorout` is to highlight normal output, mostly to help users quickly distinguish text from numbers, such as in regression tables. We have a simple `addPattern` function, but a dot (`.`) isn't recognized as a special character and the pattern `"#.*"` will not work.

When using `R.nvim,` you may get better results not loading `colorout` in your `~/.Rprofile`:

```r
if (Sys.getenv("RNVIM_TMPDIR") == "") {
    require("colorout", quietly = TRUE)
}
```

**Comment by jalvesaq** [comment]
I'm sorry, but the requested feature is beyond the scope of `colorout` and will not be implemented.
