### ISSUE TITLE
Release on R-universe / R-multiverse?

### ISSUE THREAD

**Issue by eitsupi** [jalvesaq/colorout#42]
Hello.
I have recently found it very useful to release a package on R-multiverse (<https://r-multiverse.org/>) that cannot exist on CRAN, and considering that this package is regularly released on GitHub, it would be useful to add this package to R-multiverse.
Some packages I maintain cannot exist on CRAN, so the recommended installation method is via R-multiverse:

- https://github.com/pola-rs/r-polars
- https://github.com/eitsupi/r-glaredb

I wanted to ask if it is possible to put this package on R-universe (<https://r-universe.dev/>), since a quick check shows that there are currently no users who have `colorout` on R-universe.

@eddelbuettel Sorry to ask you, but do you have any views on this? I found out about this package through your post (https://github.com/Rdatatable/data.table/issues/5425#issuecomment-1200456923).

**Comment by eddelbuettel** [comment]
Hi @eitsupi I have been using this package for years and love it as I work on the console a lot.  So I second the idea.  It takes close to no work to set this up --- @jalvesaq if you are lost in the somewhat sprawling r-universe docs let us know --- and will provide binaries on each commit to the main branch.

**Comment by eitsupi** [comment]
> I cannot comment on r-multiverse. Doing r-universe seems 'good enough' and equivalent here as the package has no dependencies. Whether or not it bubbles up into another meta repository is a second question.

Thank you for the additional explanation.
I was short on words; I think R-multiverse is guaranteed release builds (built from commits tied to GitHub releases), so users will be more comfortable using it.
Also, since it is not possible to distribute the same package twice in an individual R-universe repository, developers have to choose between a release build and a development build for each package, but since R-multiverse can take care of release builds, developers can use the development build in their personal universe.

**Comment by eddelbuettel** [comment]
All true but largely marginal (in my eyes).  Right now `colourout` has no repo to get packages from at all, adding r-universe adds that.  That is a very good first step.

**Comment by jalvesaq** [comment]
Can someone else add `colorout` to R-multiverse, or am I the only one who can do that?

**Comment by jalvesaq** [comment]
I will release a new version soon. I'm waiting for the last commit to become one month old, but since nobody reported anything, I can release the new version immediately.

**Comment by eddelbuettel** [comment]
> Can someone else add colorout to R-multiverse, or am I the only one who can do that?

Both, kind of. If you want 'your' r-universe you have to follow the steps here: https://github.com/r-universe-org/help#how-to-setup-your-personal-universe -- you install the '(web) app' to connect your repositories via your github handle to r-universe itself.  By default it will build all R packages.  You can control more finely via a simple JSON file `packages.json`.  

It is an 'open' network just like git(hub) repos are.  So on lark I added `colorout` to my universe (and will likely remove it) but now you visit [this page](https://eddelbuettel.r-universe.dev/colorout) to see what is generated: packages, binaries, docs, ...

**Comment by jalvesaq** [comment]
I would be grateful if someone else could make `colorout` publically available on R-multiverse.

**Comment by eddelbuettel** [comment]
I am pretty sure that @eitsupi can do that given that even `tinytest` appears in the (currently 34) packages there (and as a 'remote').

**Comment by eitsupi** [comment]
Thanks, I have sent a PR for that: r-multiverse/contributions#203

**Comment by eddelbuettel** [comment]
@eitsupi BTW Linux (ie Ubuntu 'noble') binaries work in r-universe so one can install that way without compiling, ie after starting a rocker/r2u:noble container this just works

```r
install.packages("colorout", repos="https://eddelbuettel.r-universe.dev/bin/linux/noble/4.4")
```

Turns out the exact same thing also works for r-multiverse so this got me `glaredb` as well as `nanoarrow`:

```r
install.packages("glaredb", repos="https://community.r-multiverse.org/bin/linux/noble/4.4")
```

Might be handy to document that somewhere.

**Comment by eitsupi** [comment]
Seems working fine.
https://community.r-multiverse.org/colorout

**Comment by jalvesaq** [comment]
Thank you, @eitsupi and @eddelbuettel !
