### ISSUE TITLE
Add option to colorize non-interactive terminals

### ISSUE THREAD

**Issue by rmatev** [jalvesaq/colorout#5]
I find it useful to have colorized output from non-interactive running with Rscript. Currently, I use `options(colorout.anyterm = TRUE)`, but this requires complications to avoid messing up with RStudio.

How about a new option, e.g. `options(colorout.noninteractive = TRUE)`, which if set, ignores the check with `interactive()`?

**Comment by jalvesaq** [comment]
If you put this in your `~/.Rprofile`
```s
interactive()
isatty(stdout())
```
and run, for instance, `R CMD INSTALL colorout_1.1-0.tar.gz`, you will see that sometimes `isatty(stdout())` is `TRUE` even when `interactive()` is `FALSE`. We have to decide whether the option `colorout.noninteractive` will affect both cases or it is better to create the option `colorout.notatty`.

**Comment by rmatev** [comment]
I'm not sure I understood. To my mind output should never be colorized when `isatty(stdout())` is `FALSE`. I am mostly interested in the colorizing regardless of `interactive()` but respecting `isatty(stdout())==FALSE`, RStudio check, etc. Mainly in this case:
```
$ Rscript -e "c(interactive(), isatty(stdout()))"
[1] FALSE  TRUE
```

**Comment by jalvesaq** [comment]
Perhaps instead of creating new options, we can simply improve the documentation with a useful example. This way we don't need to foresee all possible user cases. I could add this:

You can use any arbitrary condition to decide whether to load colorout or not. For instance:
```r
if((interactive() && Sys.getenv("RSTUDIO") == "") ||
   (interactive() == FALSE && isatty(stdout()))){
    options(colorout.anyterm = TRUE)
    library(colorout)
}
```

**Comment by rmatev** [comment]
Currently, I use something very similar to this, but it felt a little ugly so I made this ticket. I would slightly prefer a new option, but having this as an example is a very good idea too.

**Comment by jalvesaq** [comment]
One may for example want to save the output with colors in a file and then convert it into html.  In this case, `isatty(stdout())` would be `FALSE`.

I am going to do both: add the new options and the example.

**Comment by rmatev** [comment]
Great, thanks!

**Comment by jalvesaq** [comment]
Done: https://github.com/jalvesaq/colorout/commit/7829ef04c50da5804cbf4a14164c1a5a766cab6e
