### ISSUE TITLE
Request: Alternative color schemes

### ISSUE THREAD

**Issue by adefazio** [jalvesaq/colorout#6]
I use a white background on my terminals which makes most of the colors used unreadable. It would be great if there was a separate palette for light-background terminals.

**Comment by jalvesaq** [comment]
You can customize the colors. Please, do:

```r
show256Colors() # Hover the mouse over the cells
help("setOutputColors256") # See the examples section
```

You can put your `setOutputColors256` command in your `~/.Rprofile`, and also post it here because others may like your color scheme.
