### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by ultinomics** [jalvesaq/colorout#8]
I get the following errors when installing on a clean OS install with new everything (including R)l...

```
> devtools::install_github("jalvesaq/colorout")
...
* installing *source* package ‘colorout’ ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -DPLATFORM_PKGTYPE='"mac.binary.mavericks"'    -fPIC  -Wall -mtune=core2 -g -O2  -c colorout.c -o colorout.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/X11/lib -L/usr/local/lib /usr/local/lib/libcairo.a /usr/local/lib/libpixman-1.a /usr/local/lib/libfreetype.a /usr/local/lib/libfontconfig.a -lxml2 /usr/local/lib/libreadline.a -o colorout.so colorout.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
clang: error: no such file or directory: '/usr/local/lib/libcairo.a'
clang: error: no such file or directory: '/usr/local/lib/libpixman-1.a'
clang: error: no such file or directory: '/usr/local/lib/libfreetype.a'
clang: error: no such file or directory: '/usr/local/lib/libfontconfig.a'
make: *** [colorout.so] Error 1
ERROR: compilation failed for package ‘colorout’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/colorout’
Error: Command failed (1)
```

I've found that the solution was to do the following (assuming one used Homebrew):

```
$ brew install readline
$ brew link --force readline
$ brew install cairo
```

Perhaps add this to your README?

**Comment by jalvesaq** [comment]
The package does not depend on readline, freetype, X11, libpxman, libfontconfig, xml2 or cairo. It depends only on libc and libR. See the output of `ldd colorout.so`:

```
linux-vdso.so.1 =>  (0x00007ffdfb966000)
libR.so => not found
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff9d2d10000)
/lib64/ld-linux-x86-64.so.2 (0x0000558b1c38c000)
```

In the above output, `libR.so` was not found because I use R directly in its source directory.

I don't use devtools.

**Comment by jalvesaq** [comment]
I changed the README.md and I no longer strongly suggest the use of devtools since I don't use it myself: https://github.com/jalvesaq/colorout/commit/6d84420132229270329c49cc7c5978a7357ed856

**Comment by jalvesaq** [comment]
@ultinomics  I don't know how you have done this, but I believe that you have configured R to pass the arguments requiring all that libraries to the C compiler. Can you confirm this?

**Comment by ultinomics** [comment]
Hmm. Not sure how to confirm this but my gut tells me that perhaps this is an interaction between the package and [MRO](https://mran.microsoft.com/download/) (Revolution Open R). I'm not using the standard R release and, other than installing MRO, I never did any configurations. I tried installing `colorout` before ever opening MRO on this new OS X install.

**Comment by jalvesaq** [comment]
I am closing the issue because I found a report of similar problem and, as you suspected, the bug only affects MRO: http://stackoverflow.com/questions/35687820/osx-rcpp-sourcecpp-errors (post 2, comment 1).
