### ISSUE TITLE
Colorize r input

### ISSUE THREAD

**Issue by toomey8** [jalvesaq/colorout#9]
Issue #7 covers how to colorize the prompt but I was wondering it there is a way to cover the r input. I can't find it anywhere despite extensive searching. Thanks!

**Comment by jalvesaq** [comment]
As far as I know, it is impossible. The input color is defined by the terminal emulator. We can only insert color codes to make the terminal colorize the output. That said, Fish shell is pointed as a possible solution at the end of the thread: http://stackoverflow.com/questions/9780100/colorize-stdin-in-terminal

If you use Vim, you could switch to Neovim, which can colorize R input if running R in a Neovim buffer. Please, see the screenshot at https://github.com/jalvesaq/Nvim-R and the option `Rout_more_colors`.

**Comment by toomey8** [comment]
Thanks, that's useful. I'll look into neovim (I had been using tmux). Appreciate it!

**Comment by jalvesaq** [comment]
I'm closing the issue. Please, open it again if you find a way of R colorizing the input.
